# Generated by Django 4.1.6 on 2023-02-07 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
